Exten/Controllers/CategoriesForumsController.cs
using Exten.Models;
using Exten.Models.Data;
using Exten.ViewModels.CategoriesForum;
using Exten.ViewModels.CategoriesProduct;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Exten.Controllers
{
    public class CategoriesForumsController : Controller
    {
        private readonly AppCtx _context;

        public CategoriesForumsController(AppCtx context)
        {
            _context = context;
        }

        // GET: CategoriesForums
        public async Task<IActionResult> Index()
        {
              return _context.CategoriesForum != null ? 
                          View(await _context.CategoriesForum.ToListAsync()) :
                          Problem("Entity set 'AppCtx.CategoriesForum'  is null.");
        }

        // GET: CategoriesForums/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.CategoriesForum == null)
            {
                return NotFound();
            }

            var categoriesForum = await _context.CategoriesForum
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoriesForum == null)
            {
                return NotFound();
            }

            return View(categoriesForum);
        }


        //11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        // GET: CategoriesProduct/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCategoriesForumViewModel model)
        {

            if (_context.CategoriesForum
                .Where(f => f.ForumCategoryName == model.ForumCategoryName)
                .FirstOrDefault() != null
                )
            {
                ModelState.AddModelError("", "Введеная категория уже существует");
            }

            if (ModelState.IsValid)
            {
                CategoriesForum categoriesforum = new()
                {
                    ForumCategoryName = model.ForumCategoryName,
                };
                _context.Add(categoriesforum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        //11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        // GET: CategoriesForums/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.CategoriesForum == null)
            {
                return NotFound();
            }

            var categoriesForum = await _context.CategoriesForum.FindAsync(id);
            if (categoriesForum == null)
            {
                return NotFound();
            }
            return View(categoriesForum);
        }

        // POST: CategoriesForums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,ForumCategoryName")] CategoriesForum categoriesForum)
        {
            if (id != categoriesForum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoriesForum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriesForumExists(categoriesForum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoriesForum);
        }

        // GET: CategoriesForums/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.CategoriesForum == null)
            {
                return NotFound();
            }

            var categoriesForum = await _context.CategoriesForum
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoriesForum == null)
            {
                return NotFound();
            }

            return View(categoriesForum);
        }

        // POST: CategoriesForums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.CategoriesForum == null)
            {
                return Problem("Entity set 'AppCtx.CategoriesForum'  is null.");
            }
            var categoriesForum = await _context.CategoriesForum.FindAsync(id);
            if (categoriesForum != null)
            {
                _context.CategoriesForum.Remove(categoriesForum);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriesForumExists(short id)
        {
          return (_context.CategoriesForum?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Exten/Controllers/ForumController.cs
using Exten.Models;
using Exten.Models.Data;
using Exten.ViewModels.Forum;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Exten.Controllers
{
    public class ForumController : Controller
    {
        private readonly AppCtx _context;

        public ForumController(AppCtx context)
        {
            _context = context;
        }

        // GET: Forum
        public async Task<IActionResult> Index()
        {
            var appCtx = _context.Forums
                .Include(a => a.CategoriesForum)
                .Include(a => a.User)
                .OrderBy(o => o.ForumTopic);

            return _context.Forums != null ?
                          View(await appCtx.ToListAsync()) :
                          Problem("Entity set 'AppCtx.Forums'  is null.");
        }

        // GET: Forum/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.Forums == null)
            {
                return NotFound();
            }

            var forum = await _context.Forums
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // GET: Forum/Create
        public IActionResult Create()
        {
            ViewData["IdCategoryForum"] = new SelectList(_context.CategoriesForum.OrderBy(o => o.ForumCategoryName), "Id", "ForumCategoryName");
          
            ViewData["IdUser"] = new SelectList(_context.Users.OrderBy(o => o.Email), "Id", "Email");
            return View();
        }

        // POST: AnimeTitles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateForumViewModel model)
        {
            if (_context.Forums
                .Where(f => f.ForumTopic == model.ForumTopic &&
                    f.ForumMessage == model.ForumMessage &&
                    f.DateCreation == model.DateCreation &&
                    f.IdCategoryForum == model.IdCategoryForum &&
                    f.IdUser == model.IdUser)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеный товар уже существует");
            }

            if (ModelState.IsValid)
            {
                Forum forum = new()
                {
                    ForumTopic = model.ForumTopic,
                    ForumMessage = model.ForumMessage,
                    DateCreation = model.DateCreation,
                    IdCategoryForum = model.IdCategoryForum,
                    IdUser = model.IdUser
                };

                _context.Add(forum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdCategoryForum"] = new SelectList(_context.CategoriesProduct.OrderBy(o => o.CategoryName), "Id", "ForumCategoryName");

            ViewData["IdUser"] = new SelectList(_context.User.OrderBy(o => o.IdUser), "Id", "IdUser");
            return View(model);
        }
            // GET: Forum/Edit/5
            public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.Forums == null)
            {
                return NotFound();
            }

            var forum = await _context.Forums.FindAsync(id);
            if (forum == null)
            {
                return NotFound();
            }
            ViewData["IdUser"] = new SelectList(_context.Users, "Id", "Id", forum.IdUser);
            return View(forum);
        }

        // POST: Forum/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,ProductName,PriceProduct,RegistrationDate,IdCategoryProduct,IdUser")] Forum forum)
        {
            if (id != forum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumExists(forum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdUser"] = new SelectList(_context.Users, "Id", "Id", forum.IdUser);
            return View(forum);
        }

        // GET: Forum/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.Forums == null)
            {
                return NotFound();
            }

            var forum = await _context.Forums
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // POST: Forum/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.Forums == null)
            {
                return Problem("Entity set 'AppCtx.Forum'  is null.");
            }
            var forum = await _context.Forums.FindAsync(id);
            if (forum != null)
            {
                _context.Forums.Remove(forum);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ForumExists(short id)
        {
          return (_context.Forums?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Exten/Controllers/ProductsController.cs
using Exten.Models;
using Exten.Models.Data;
using Exten.ViewModels.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Exten.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppCtx _context;

        public ProductsController(AppCtx context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var appCtx = _context.Products
                .Include(a => a.CategoryProduct)
                .OrderBy(o => o.ProductName);

            return _context.Products != null ? 
                          View(await appCtx.ToListAsync()) :
                          Problem("Entity set 'AppCtx.Products'  is null.");
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["IdCategoryProduct"] = new SelectList(_context.CategoriesProduct.OrderBy(o => o.CategoryName), "Id", "CategoryName");
            return View();
        }

        // POST: AnimeTitles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductViewModel model)
        {
            if (_context.Products
                .Where(f => f.ProductName == model.ProductName &&
                    f.PriceProduct == model.PriceProduct &&
                    f.IdCategoryProduct == model.IdCategoryProduct)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеный товар уже существует");
            }

            if (ModelState.IsValid)
            {
                Product products = new()
                {
                    ProductName = model.ProductName,
                    PriceProduct = model.PriceProduct,
                    Description = model.Description,
                    IdCategoryProduct = model.IdCategoryProduct
                };

                _context.Add(products);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdCategoryProduct"] = new SelectList(_context.CategoriesProduct.OrderBy(o => o.CategoryName), "Id", "CategoryName", model.IdCategoryProduct);
            return View(model);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,ProductName,PriceProduct,Description,IdCategoryProduct")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'AppCtx.Products'  is null.");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(short id)
        {
          return (_context.Products?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Exten/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exten</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (IsSectionDefined("Header"))
                    {
                        @RenderSection("Header")
                    }
                    else
                    {
                        //если пользователь вошел в систему
                        @if (User.Identity.IsAuthenticated)
                        {
                            // то он видит вкладку "Главная"
                            <ul class="navbar-nav flex-grow">
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index" title="Главная">
                                        <i class="fas fa-home"></i>
                                    </a>
                                </li>

                                <li class="nav-item dropdown">
@*                                     <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">
                                        <i class="fas fa-chalkboard-teacher"></i>  Информация об обучении
                                    </a> *@
                                    <div class="dropdown-menu">
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoriesProduct" asp-action="Index">Категории товаров</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Магазин</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoriesForums" asp-action="Index">Категории форума</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="Index">Форум</a>
                                        </li>
                                    </div>
                                </li>
                            </ul>

                    // с левой стороны, пользователь видит свой свою почту с выпадающим меню
                            // одним из пункта меню является выход
                            <ul class="navbar-nav flex-grow">
                                <li>
                                    <a class="nav-link text-dark">
                                        <i class="far fa-user-circle"></i>  @User.Identity.Name
                                    </a>
                                </li>
                                <li>
                                    <form class="form-inline" method="post" asp-controller="Account" asp-action="Logout">                                    
                                            <input class="btn btn-link text-dark" type="submit" value="Выход" />
                                    </form>
                                </li>
                            </ul>

                        }
                        // если пользователь не вошел на сайт, то для него отображается в качестве главной страницы вход в систему
                        else
                        {
                            <ul class="navbar-nav">
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Login" title="Главная">
                                        <i class="fas fa-home"></i>
                                    </a>
                                </li>
                            </ul>
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">
                                        <i class="fas fa-sign-in-alt"></i>  Вход
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Регистрация</a>
                                </li>
                            </ul>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:80px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @*добавление текущего года в footer*@
            &copy; @DateTime.Today.Year - Exten 🦔
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>