Exten/ViewModels/CategoriesProduct/CreateCategoriesProductViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Exten.ViewModels.CategoriesProduct
{
    public class CreateCategoriesProductViewModel
    {
        [Required(ErrorMessage = "Введите название категории товаров")]
        [Display(Name = "Категория")]
        public string CategoryName { get; set; }
    }
}

Exten/ViewModels/CategoriesProduct/EditCategoryProductViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Exten.ViewModels.CategoriesProduct
{
    public class EditCategoryProductViewModel
    {

        public short Id { get; set; }
        [Required(ErrorMessage = "Введите название категории товаров")]
        [Display(Name = "Категория")]
        public string CategoryName { get; set; }
    }
}

Exten/Controllers/CategoriesProductController.cs
using Exten.Models;
using Exten.Models.Data;
using Exten.ViewModels.CategoriesProduct;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Exten.Controllers
{
    public class CategoriesProductController : Controller
    {
        private readonly AppCtx _context;

        public CategoriesProductController(AppCtx context)
        {
            _context = context;
        }

        // GET: CategoriesProduct
        public async Task<IActionResult> Index()
        {
            var appCtx = _context.CategoriesProduct
                .OrderBy(f => f.CategoryName);

            return _context.CategoriesProduct != null ? 
                        View(await _context.CategoriesProduct.ToListAsync()) :
                        Problem("Entity set 'AppCtx.CategoriesProduct'  is null.");
        }

        // GET: CategoriesProduct/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.CategoriesProduct == null)
            {
                return NotFound();
            }

            var categoryProduct = await _context.CategoriesProduct
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoryProduct == null)
            {
                return NotFound();
            }

            return View(categoryProduct);
        }

        // GET: CategoriesProduct/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCategoriesProductViewModel model)
        {

            if (_context.CategoriesProduct
                .Where(f => f.CategoryName == model.CategoryName)
                .FirstOrDefault() != null
                )
            {
                ModelState.AddModelError("", "Введеная категория уже существует");
            }

            if (ModelState.IsValid)
            {
                CategoryProduct categoryProduct = new()
                {
                    CategoryName = model.CategoryName,
                };
                _context.Add(categoryProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        // GET: CategoriesProduct/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.CategoriesProduct == null)
            {
                return NotFound();
            }

            var categoryProduct = await _context.CategoriesProduct.FindAsync(id);
            if (categoryProduct == null)
            {
                return NotFound();
            }
            return View(categoryProduct);
        }

        // POST: CategoriesProduct/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,CategoryName")] CategoryProduct categoryProduct)
        {
            if (id != categoryProduct.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryProduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryProductExists(categoryProduct.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoryProduct);
        }

        // GET: CategoriesProduct/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.CategoriesProduct == null)
            {
                return NotFound();
            }

            var categoryProduct = await _context.CategoriesProduct
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoryProduct == null)
            {
                return NotFound();
            }

            return View(categoryProduct);
        }

        // POST: CategoriesProduct/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.CategoriesProduct == null)
            {
                return Problem("Entity set 'AppCtx.CategoriesProduct'  is null.");
            }
            var categoryProduct = await _context.CategoriesProduct.FindAsync(id);
            if (categoryProduct != null)
            {
                _context.CategoriesProduct.Remove(categoryProduct);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryProductExists(short id)
        {
          return (_context.CategoriesProduct?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Exten/Views/CategoriesProduct/Create.cshtml
@model Exten.ViewModels.CategoriesProduct.CreateCategoriesProductViewModel;
@{
    ViewData["Title"] = "Создание категории";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="CategoriesProduct" asp-action="Index">Категории товаров</a></li>
        <li class="breadcrumb-item active">Создание</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление категории
</h3>
<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="CategoriesProduct" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Exten/Views/CategoriesProduct/Delete.cshtml
@model Exten.Models.Data.CategoryProduct

@{
    ViewData["Title"] = "Удаление";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="CategoriesProduct" asp-action="Index">Категории товаров</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление категории
</h3>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <br>
        <input type="submit" value="Удалить" class="btn btn-danger"/>
    </form>
</div>

Exten/Views/CategoriesProduct/Details.cshtml
@model Exten.Models.Data.CategoryProduct

@{
    ViewData["Title"] = "Просмотр";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="CategoriesProduct" asp-action="Index">Категории товаров</a></li>
        <li class="breadcrumb-item active">Просмотр категории</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Просмотр категории
</h3>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Редактировать</a>
</div>

Exten/Views/CategoriesProduct/Edit.cshtml
@model Exten.Models.Data.CategoryProduct

@{
    ViewData["Title"] = "Edit";
}


<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="CategoriesProduct" asp-action="Index">Категории товаров</a></li>
        <li class="breadcrumb-item active">Редактирование категории</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Редактирование категории
</h3>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form> 
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Exten/Views/CategoriesProduct/Index.cshtml
@model IEnumerable<Exten.Models.Data.CategoryProduct>

@{
    ViewData["Title"] = "Категории товаров";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item active">Категории товаров</li>
    </ol>
</nav>
<h2>Категории товаров</h2>

<h6>
    <a class="btn text-dark" asp-action="Create">
        <i class="far fa-plus-square"></i>  Добавить категорию товаров
    </a>
</h6>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewBag.FormOfEduSort">
                    @Html.DisplayNameFor(model => model.CategoryName)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    <a class="btn text-dark" asp-action="Details" asp-route-id="@item.Id" title="Посмотреть подробнее">
                        <i class="far fa-eye"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Edit" asp-route-id="@item.Id" title="Редактировать">
                        <i class="fas fa-pencil-alt"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Delete" asp-route-id="@item.Id" title="Удалить">
                        <i class="far fa-minus-square"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>